repos:
  -
    name: example1
    allow_auto_merge: true
    allow_merge_commit: false
    allow_rebase_merge: false
    allow_squash_merge: true
    archived: false
    delete_branch_on_merge: true
    description: This is a test repository
    squash_merge_commit_message: COMMIT_MESSAGES
    squash_merge_commit_title: PR_TITLE
    visibility: private
    allow_update_branch: true
  -
    name: example2
    allow_auto_merge: true
    allow_merge_commit: false
    allow_rebase_merge: false
    allow_squash_merge: true
    archived: false
    delete_branch_on_merge: true
    description: This is a test repository
    squash_merge_commit_message: COMMIT_MESSAGES
    squash_merge_commit_title: PR_TITLE
    visibility: private
    allow_update_branch: true